package multitreading;

class MyThread extends Thread{}

public class TestName {
    public static void main(String args[]){
        System.out.println(Thread.currentThread().getName());           //returns thread name

        MyThread t = new MyThread();
        System.out.println(t.getName());                                //default name generated by jvm. 

        Thread.currentThread().setName("boss main");
        System.out.println(Thread.currentThread().getName());           //returns new name of thrad.

        System.out.println(10/0);                                       //exception in changed name of thread
    }
}
